#!/usr/bin/env python3
"""Sprite Compiler for Atari 8-bit Jabberwocky Project.

Parses sprite definitions from JSON format (Sprite Studio SSOT) and generates
clean MOS 6502 MADS assembly data in Structure-of-Arrays (SoA) layout.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass, field
import json
from pathlib import Path
import sys
from typing import List


@dataclass
class SpriteFrame:
    """Single 2D frame containing binary pixel strings."""

    pixels: List[str] = field(default_factory=list)


@dataclass
class SpriteData:
    """Sprite definition including dimensions and animation frames."""

    id: str
    width: int
    height: int
    color: int
    frame_duration: int
    frames: List[SpriteFrame] = field(default_factory=list)


def load_sprite_json(json_path: Path) -> SpriteData:
    """Parse and validate sprite project JSON."""
    if not json_path.exists():
        raise FileNotFoundError(f"Sprite JSON file not found: {json_path}")

    with json_path.open("r", encoding="utf-8") as f:
        data = json.load(f)

    sprites = data.get("sprites", [])
    if not sprites:
        raise ValueError(f"No sprites defined in {json_path}")

    s0 = sprites[0]
    width = int(s0.get("width", 8))
    height = int(s0.get("height", 21))
    color = int(s0.get("color", 0))
    anim = s0.get("animation", {})
    frame_duration = int(anim.get("frame_duration", 5))

    raw_frames = s0.get("frames", [])
    if not raw_frames:
        raise ValueError("Sprite has no animation frames")

    frames: List[SpriteFrame] = []
    for f_idx, f_data in enumerate(raw_frames):
        pixel_lines = f_data.get("pixels", [])
        if len(pixel_lines) != height:
            raise ValueError(
                f"Frame {f_idx} height mismatch: expected {height}, got {len(pixel_lines)}"
            )
        for line_idx, line in enumerate(pixel_lines):
            line_str = str(line).strip()
            if len(line_str) != width:
                raise ValueError(
                    f"Frame {f_idx} line {line_idx} width mismatch: expected {width}, got {len(line_str)}"
                )
            if not all(c in "01" for c in line_str):
                raise ValueError(
                    f"Frame {f_idx} line {line_idx} contains non-binary characters: {line_str}"
                )
        frames.append(SpriteFrame(pixels=[str(l).strip() for l in pixel_lines]))

    return SpriteData(
        id=str(s0.get("id", "SPRITE_0")),
        width=width,
        height=height,
        color=color,
        frame_duration=frame_duration,
        frames=frames,
    )


def generate_mads_assembly(sprite: SpriteData, prefix: str = "dragon") -> str:
    """Generate MADS 6502 assembly source with Structure-of-Arrays (SoA) layout."""
    lines: List[str] = [
        "; ==============================================================================",
        f"; AUTO-GENERATED SPRITE DATA — {prefix.upper()}",
        f"; Source: {sprite.id} ({len(sprite.frames)} frames, {sprite.width}x{sprite.height})",
        "; DO NOT EDIT MANUALLY — Generated by scripts/compile_sprites.py",
        "; ==============================================================================",
        "",
        f"{prefix.upper()}_SPRITE_W     = {sprite.width}",
        f"{prefix.upper()}_SPRITE_H     = {sprite.height}",
        f"{prefix.upper()}_FRAME_COUNT  = {len(sprite.frames)}",
        f"{prefix.upper()}_DEFAULT_DUR  = {sprite.frame_duration}",
        "",
    ]

    # Generate each frame as consecutive byte lines
    for i, frame in enumerate(sprite.frames):
        lines.append(f"{prefix}_frame_{i}")
        for pixel_line in frame.pixels:
            lines.append(f"    dta %{pixel_line}")
        lines.append("")

    # Generate Structure-of-Arrays (SoA) lookup tables for 6502 indexed addressing
    lines.append("; Structure-of-Arrays (SoA) Frame Address Lookup Tables")
    lo_labels = ", ".join(f"<{prefix}_frame_{i}" for i in range(len(sprite.frames)))
    hi_labels = ", ".join(f">{prefix}_frame_{i}" for i in range(len(sprite.frames)))

    lines.append(f"{prefix}_frame_tbl_lo")
    lines.append(f"    dta {lo_labels}")
    lines.append("")
    lines.append(f"{prefix}_frame_tbl_hi")
    lines.append(f"    dta {hi_labels}")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Compile Atari sprite JSON into MADS assembly."
    )
    parser.add_argument(
        "-i", "--input",
        required=True,
        help="Input JSON file (e.g. sprites/jabberwocky.json)",
    )
    parser.add_argument(
        "-o", "--output",
        required=True,
        help="Output ASM file (e.g. gen/dragon_sprite.asm)",
    )
    parser.add_argument(
        "--prefix",
        default="dragon",
        help="Label prefix for generated assembly (default: 'dragon')",
    )

    args = parser.parse_args()
    input_path = Path(args.input)
    output_path = Path(args.output)

    try:
        sprite = load_sprite_json(input_path)
        asm_code = generate_mads_assembly(sprite, prefix=args.prefix)

        output_path.parent.mkdir(parents=True, exist_ok=True)
        with output_path.open("w", encoding="utf-8") as f:
            f.write(asm_code)

        print(
            f"Successfully compiled sprite '{sprite.id}' ({len(sprite.frames)} frames) "
            f"to {output_path}"
        )
        return 0
    except Exception as e:
        print(f"Error compiling sprite: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
