#!/usr/bin/env python3
"""Text Compiler for Atari 8-bit Jabberwocky Project.

Converts plain text files (UTF-8) with Polish diacritics into MADS assembly
data structures in gen/, mapping characters to ANTIC internal screen display codes.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
from typing import List, Tuple

# Polish diacritics mapping for custom font (fonts/text.fnt)
# Standard ANTIC internal display codes:
# 64..72: ą, ć, ę, ł, ń, ó, ś, ź, ż
# 73..81: Ą, Ć, Ę, Ł, Ń, Ó, Ś, Ź, Ż
POLISH_CHAR_MAP = {
    'ą': 64, 'ć': 65, 'ę': 66, 'ł': 67, 'ń': 68, 'ó': 69, 'ś': 70, 'ź': 71, 'ż': 72,
    'Ą': 73, 'Ć': 74, 'Ę': 75, 'Ł': 76, 'Ń': 77, 'Ó': 78, 'Ś': 79, 'Ź': 80, 'Ż': 81,
}


def text_to_mads_dta(text: str, invert: bool = False, length_prefix: bool = False) -> List[str]:
    """Convert a string into MADS dta statements with ANTIC display codes."""
    lines: List[str] = []
    inv_flag = "*" if invert else ""
    inv_byte = 0x80 if invert else 0x00

    if length_prefix:
        lines.append(f"    dta {len(text)}")

    chunks: List[Tuple[str, str | int]] = []
    cur_ascii: List[str] = []

    for ch in text:
        if ch in POLISH_CHAR_MAP:
            if cur_ascii:
                chunks.append(('str', ''.join(cur_ascii)))
                cur_ascii = []
            chunks.append(('code', POLISH_CHAR_MAP[ch] + inv_byte))
        else:
            cur_ascii.append(ch)

    if cur_ascii:
        chunks.append(('str', ''.join(cur_ascii)))

    for kind, val in chunks:
        if kind == 'str':
            # Escape single quotes in MADS string if needed
            escaped = str(val).replace("'", "''")
            lines.append(f"    dta d'{escaped}'{inv_flag}")
        else:
            lines.append(f"    dta {val}")

    return lines


def compile_title_text(src_path: Path) -> str:
    """Compile texts/title.txt into intro poem line structures."""
    if not src_path.exists():
        raise FileNotFoundError(f"Source file not found: {src_path}")

    with src_path.open("r", encoding="utf-8") as f:
        raw_lines = [line.rstrip("\r\n") for line in f if line.strip()]

    out: List[str] = [
        "; ==============================================================================",
        "; AUTO-GENERATED BY scripts/compile_texts.py — DO NOT EDIT DIRECTLY",
        f"; Source: {src_path.as_posix()}",
        "; ==============================================================================",
        "",
    ]

    for idx, line in enumerate(raw_lines, start=1):
        out.append(f"intro_txt_line{idx}")
        out.extend(text_to_mads_dta(line, invert=False, length_prefix=True))
        out.append("")

    return "\n".join(out)


def compile_scroll_text(src_path: Path) -> str:
    """Compile texts/scroll.txt into marquee scroll ticker structure."""
    if not src_path.exists():
        raise FileNotFoundError(f"Source file not found: {src_path}")

    with src_path.open("r", encoding="utf-8") as f:
        text = f.read().rstrip("\r\n")

    out: List[str] = [
        "; ==============================================================================",
        "; AUTO-GENERATED BY scripts/compile_texts.py — DO NOT EDIT DIRECTLY",
        f"; Source: {src_path.as_posix()}",
        "; ==============================================================================",
        "",
        f"TITLE_SCROLL_TEXT_LEN = {len(text)}",
        "",
        "title_scroll_text",
    ]

    out.extend(text_to_mads_dta(text, invert=True, length_prefix=False))
    out.append("")
    return "\n".join(out)


def main() -> None:
    """CLI entrypoint."""
    parser = argparse.ArgumentParser(description="Compile texts for Atari 8-bit Jabberwocky")
    parser.add_argument("--texts-dir", type=Path, default=Path("texts"), help="Directory with source text files")
    parser.add_argument("--gen-dir", type=Path, default=Path("gen"), help="Directory for generated ASM files")
    args = parser.parse_args()

    texts_dir: Path = args.texts_dir
    gen_dir: Path = args.gen_dir
    gen_dir.mkdir(parents=True, exist_ok=True)

    title_src = texts_dir / "title.txt"
    if title_src.exists():
        title_asm = gen_dir / "intro_text.asm"
        title_asm.write_text(compile_title_text(title_src), encoding="utf-8")
        print(f"Generated {title_asm} from {title_src}")

    scroll_src = texts_dir / "scroll.txt"
    if scroll_src.exists():
        scroll_asm = gen_dir / "title_scroll_text.asm"
        scroll_asm.write_text(compile_scroll_text(scroll_src), encoding="utf-8")
        print(f"Generated {scroll_asm} from {scroll_src}")


if __name__ == "__main__":
    main()
