#!/usr/bin/env python3
"""Compiler script for animated charset definitions.

Parses chars/animated.json and generates Structure-of-Arrays (SoA) assembly
tables for frame-based character animations in Atari 8-bit RAM font.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import sys
from typing import Any, Dict, List


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate animated charset assembly from JSON definition."
    )
    parser.add_argument(
        "-i", "--input",
        required=True,
        help="Path to animated.json",
    )
    parser.add_argument(
        "-o", "--output",
        required=True,
        help="Path to output .asm file",
    )
    parser.add_argument(
        "--charset-base",
        type=lambda x: int(x, 0),
        default=0x7400,
        help="Base address of target character set in RAM (default: 0x7400 / GAME_FONT_ADDR)",
    )
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: Input file '{args.input}' does not exist.", file=sys.stderr)
        return 1

    try:
        with input_path.open("r", encoding="utf-8") as f:
            data: Dict[str, Any] = json.load(f)
    except Exception as e:
        print(f"Error reading/parsing input JSON: {e}", file=sys.stderr)
        return 1

    characters: List[Dict[str, Any]] = data.get("characters", [])
    num_chars = len(characters)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        with output_path.open("w", encoding="utf-8") as f:
            f.write("; Generated by gen_animated_charset.py. Do not edit.\n\n")
            f.write(f"NUM_ANIM_CHARS = {num_chars}\n\n")

            if num_chars == 0:
                f.write("animated_char_dest_lo\n")
                f.write("animated_char_dest_hi\n")
                f.write("animated_char_num_segments\n")
                f.write("animated_char_seg_repeats_lo\n")
                f.write("animated_char_seg_repeats_hi\n")
                f.write("animated_char_seg_num_frames_lo\n")
                f.write("animated_char_seg_num_frames_hi\n")
                f.write("animated_char_seg_frame_starts_lo\n")
                f.write("animated_char_seg_frame_starts_hi\n")
                f.write("animated_char_durations_lo\n")
                f.write("animated_char_durations_hi\n")
                f.write("animated_char_data_lo\n")
                f.write("animated_char_data_hi\n")
                f.write("animated_char_cur_segment\n")
                f.write("animated_char_repeat_counter\n")
                f.write("animated_char_init_repeats\n")
                f.write("animated_char_cur_frame\n")
                f.write("animated_char_timers\n")
                f.write("animated_char_ids\n")
                return 0

            dest_lo: List[str] = []
            dest_hi: List[str] = []
            num_segments_list: List[str] = []
            seg_repeats_lo: List[str] = []
            seg_repeats_hi: List[str] = []
            seg_num_frames_lo: List[str] = []
            seg_num_frames_hi: List[str] = []
            seg_frame_starts_lo: List[str] = []
            seg_frame_starts_hi: List[str] = []
            durations_lo: List[str] = []
            durations_hi: List[str] = []
            data_lo: List[str] = []
            data_hi: List[str] = []
            char_ids: List[str] = []
            repeat_counters_init: List[str] = []

            for idx, char_info in enumerate(characters):
                char_idx = int(char_info["index"])
                dest_addr = args.charset_base + char_idx * 8
                dest_lo.append(f"<{dest_addr}")
                dest_hi.append(f">{dest_addr}")

                raw_anim = char_info.get("animation", [])
                if (
                    raw_anim
                    and isinstance(raw_anim[0], dict)
                    and "duration" in raw_anim[0]
                    and "data" in raw_anim[0]
                ):
                    segments = [{"repeat": 0, "frames": raw_anim}]
                else:
                    segments = raw_anim

                num_segments = len(segments)
                num_segments_list.append(str(num_segments))

                flat_frames: List[Dict[str, Any]] = []
                for seg in segments:
                    flat_frames.extend(seg.get("frames", []))

                num_flat_frames = len(flat_frames)
                if num_flat_frames > 32:
                    print(
                        f"Warning: Character at index {char_idx} has {num_flat_frames} frames "
                        f"(recommended max is 32).",
                        file=sys.stderr,
                    )

                seg_repeats_lo.append(f"<char{idx}_segment_repeats")
                seg_repeats_hi.append(f">char{idx}_segment_repeats")

                seg_num_frames_lo.append(f"<char{idx}_segment_num_frames")
                seg_num_frames_hi.append(f">char{idx}_segment_num_frames")

                seg_frame_starts_lo.append(f"<char{idx}_segment_frame_starts")
                seg_frame_starts_hi.append(f">char{idx}_segment_frame_starts")

                durations_lo.append(f"<char{idx}_durations")
                durations_hi.append(f">char{idx}_durations")

                data_lo.append(f"<char{idx}_data")
                data_hi.append(f">char{idx}_data")

                char_ids.append(str(char_idx))

                initial_repeat = segments[0].get("repeat", 0) if num_segments > 0 else 0
                repeat_counters_init.append(str(initial_repeat))

            f.write("animated_char_dest_lo\n")
            f.write(f"\tdta {', '.join(dest_lo)}\n\n")

            f.write("animated_char_dest_hi\n")
            f.write(f"\tdta {', '.join(dest_hi)}\n\n")

            f.write("animated_char_num_segments\n")
            f.write(f"\tdta {', '.join(num_segments_list)}\n\n")

            f.write("animated_char_seg_repeats_lo\n")
            f.write(f"\tdta {', '.join(seg_repeats_lo)}\n\n")

            f.write("animated_char_seg_repeats_hi\n")
            f.write(f"\tdta {', '.join(seg_repeats_hi)}\n\n")

            f.write("animated_char_seg_num_frames_lo\n")
            f.write(f"\tdta {', '.join(seg_num_frames_lo)}\n\n")

            f.write("animated_char_seg_num_frames_hi\n")
            f.write(f"\tdta {', '.join(seg_num_frames_hi)}\n\n")

            f.write("animated_char_seg_frame_starts_lo\n")
            f.write(f"\tdta {', '.join(seg_frame_starts_lo)}\n\n")

            f.write("animated_char_seg_frame_starts_hi\n")
            f.write(f"\tdta {', '.join(seg_frame_starts_hi)}\n\n")

            f.write("animated_char_durations_lo\n")
            f.write(f"\tdta {', '.join(durations_lo)}\n\n")

            f.write("animated_char_durations_hi\n")
            f.write(f"\tdta {', '.join(durations_hi)}\n\n")

            f.write("animated_char_data_lo\n")
            f.write(f"\tdta {', '.join(data_lo)}\n\n")

            f.write("animated_char_data_hi\n")
            f.write(f"\tdta {', '.join(data_hi)}\n\n")

            cur_segments_init = ["0" for _ in range(num_chars)]
            f.write("animated_char_cur_segment\n")
            f.write(f"\tdta {', '.join(cur_segments_init)}\n\n")

            f.write("animated_char_repeat_counter\n")
            f.write(f"\tdta {', '.join(repeat_counters_init)}\n\n")

            f.write("animated_char_init_repeats\n")
            f.write(f"\tdta {', '.join(repeat_counters_init)}\n\n")

            cur_frames_init = ["255" for _ in range(num_chars)]
            f.write("animated_char_cur_frame\n")
            f.write(f"\tdta {', '.join(cur_frames_init)}\n\n")

            timers_init = ["1" for _ in range(num_chars)]
            f.write("animated_char_timers\n")
            f.write(f"\tdta {', '.join(timers_init)}\n\n")

            f.write("animated_char_ids\n")
            f.write(f"\tdta {', '.join(char_ids)}\n\n")

            for idx, char_info in enumerate(characters):
                f.write(f"; --- Character {char_info['index']} ---\n")
                raw_anim = char_info.get("animation", [])
                if (
                    raw_anim
                    and isinstance(raw_anim[0], dict)
                    and "duration" in raw_anim[0]
                    and "data" in raw_anim[0]
                ):
                    segments = [{"repeat": 0, "frames": raw_anim}]
                else:
                    segments = raw_anim

                repeats = [str(seg.get("repeat", 0)) for seg in segments]
                f.write(f"char{idx}_segment_repeats\n")
                f.write(f"\tdta {', '.join(repeats)}\n")

                num_frames = [str(len(seg.get("frames", []))) for seg in segments]
                f.write(f"char{idx}_segment_num_frames\n")
                f.write(f"\tdta {', '.join(num_frames)}\n")

                starts: List[str] = []
                curr_start = 0
                for seg in segments:
                    starts.append(str(curr_start))
                    curr_start += len(seg.get("frames", []))
                f.write(f"char{idx}_segment_frame_starts\n")
                f.write(f"\tdta {', '.join(starts)}\n")

                durations: List[str] = []
                for seg in segments:
                    durations.extend(
                        [str(min(int(frame["duration"]), 255)) for frame in seg.get("frames", [])]
                    )
                f.write(f"char{idx}_durations\n")
                f.write(f"\tdta {', '.join(durations)}\n")

                f.write(f"char{idx}_data\n")
                for seg in segments:
                    for frame in seg.get("frames", []):
                        hex_bytes = frame["data"].split()
                        decimal_bytes = [str(int(b, 16)) for b in hex_bytes]
                        f.write(f"\tdta {', '.join(decimal_bytes)}\n")
                f.write("\n")

    except Exception as e:
        print(f"Error writing output file: {e}", file=sys.stderr)
        return 1

    print(f"Successfully generated animated charset assembly to '{args.output}' ({num_chars} characters).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
