#!/usr/bin/env python3
"""Compiler script for rotated charset definitions.

Parses chars/rotated.json and generates assembly tables for continuous
in-place 2-bit rotation of character bitmaps in Atari 8-bit RAM font.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import sys
from typing import Any, Dict, List


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate rotated charset assembly tables from JSON definition."
    )
    parser.add_argument(
        "-i", "--input",
        required=True,
        help="Path to rotated.json",
    )
    parser.add_argument(
        "-g", "--global-out",
        required=True,
        help="Path to output global .asm file",
    )
    parser.add_argument(
        "-p", "--proc-out",
        required=True,
        help="Path to output proc .asm file",
    )
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: Input file '{args.input}' does not exist.", file=sys.stderr)
        return 1

    try:
        with input_path.open("r", encoding="utf-8") as f:
            data: Dict[str, Any] = json.load(f)
    except Exception as e:
        print(f"Error reading/parsing input JSON: {e}", file=sys.stderr)
        return 1

    characters: List[Dict[str, Any]] = data.get("characters", [])
    num_chars = len(characters)

    global_out_path = Path(args.global_out)
    proc_out_path = Path(args.proc_out)

    global_out_path.parent.mkdir(parents=True, exist_ok=True)
    proc_out_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        with global_out_path.open("w", encoding="utf-8") as f:
            f.write("; Generated by gen_rotated_charset.py. Do not edit.\n\n")
            f.write(f"ANIM_CHAR_COUNT = {num_chars}\n\n")

        with proc_out_path.open("w", encoding="utf-8") as f:
            f.write("; Generated by gen_rotated_charset.py. Do not edit.\n\n")

            char_ids = [str(char_info["index"]) for char_info in characters]
            durations = [str(char_info["duration"]) for char_info in characters]

            f.write("anim_char_ids\n")
            if num_chars > 0:
                f.write(f"\tdta {', '.join(char_ids)}\n\n")
            else:
                f.write("\n")

            f.write("anim_char_speeds\n")
            if num_chars > 0:
                f.write(f"\tdta {', '.join(durations)}\n\n")
            else:
                f.write("\n")

            f.write("anim_char_counters\n")
            if num_chars > 0:
                f.write(f"\tdta {', '.join(durations)}\n\n")
            else:
                f.write("\n")

    except Exception as e:
        print(f"Error writing output files: {e}", file=sys.stderr)
        return 1

    print(f"Successfully generated rotated charset assembly files ({num_chars} characters).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
